server:
  port: 9001
spring:
  application:
    name: exam-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.42:3306/springboot
    username: root
    password: root
mybatis:
  type-aliases-package: plus.ldl.user.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
