management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql:///springboot
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
