server:
  port: 80
  servlet:
    context-path: /ldl


name: zhangsan

spring:
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/pages/
  #      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
logging:
  level:
    plus.ldl: debug

mybatis:
  type-aliases-package: plus.ldl.domain

