server:
  port: 8001

spring:
  application:
    name: service-edu

  profiles:
    active: pro

  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.31.42/guli?serverTimezone=GMT%2B8
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#logging:
#  level:
#    root: debug
