spring:
  application:
    name: eureka-consumer

server:
  port: 8000

eureka:
  client:
    service-url:
      #            defaultZone: http://localhost:9524/eureka
      defaultZone: http://eureka-server:9524/eureka
  instance:
    hostname: eureka-consumer
