spring:
  #\u6570\u636E\u6E90
  datasource:
    url: jdbc:mysql://192.168.31.42:3306/poijob??useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: plus.ldl.excelpoijob.domain
  mapperLocations: classpath:mapper/*Mapper.xml
