server:
  port: 80

spring:
  application:
    name: api-gateway-server

  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则
      routes: #集合。
        # id: 唯一标识。默认是一个UUID
        # uri: 转发路径
        # predicates: 条件,用于请求网关路径的匹配规则
        # filters：配置局部过滤器的

        - id: eureka-provider
          # 静态路由
          # uri: http://localhost:8001/
          # 动态路由
          uri: lb://EUREKA-PROVIDER
          predicates:
            - Path=/provider/goods/**

        - id: eureka-consumer
          # uri: http://localhost:9000
          uri: lb://EUREKA-CONSUMER
          predicates:
            - Path=/consumer/order/**

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:9524/eureka
      defaultZone: http://eureka-server:9524/eureka
